### ISSUE TITLE
Add numbering to tickets.

### ISSUE THREAD

**Issue by gstephen** [Sitback/jira-sitback#2]
Can we look at adding numbering to comments on tickets, this will be particularly helpful for support when referring to previous comments with clients.

I've looked into a way of adding this through jQuery, tested it and it works well.

Thanks!

**Comment by chinthakagodawita** [comment]
@gstephen Could you put that link you found in here?

**Comment by gstephen** [comment]
http://www.renjithv.info/2013/07/29/how-to-add-numbering-for-jira-comments/

**Comment by chinthakagodawita** [comment]
@gstephen We're going to have to find a better solution - it starts numbering from '1' even when there are older comments (see screenshot)

![jira-comment-numbering](https://cloud.githubusercontent.com/assets/1452384/24278086/b3744c02-1095-11e7-8953-07e99d46b7fd.png)

**Comment by gstephen** [comment]
@chinthakagodawita I've updated it to account for collapsed comments.

![_bh-10__amend_the__endorsed_by__logos_on_the_bh_homepage_and_add_pmi_logo_-_sitback_jira](https://cloud.githubusercontent.com/assets/11155336/24336028/181ecc32-12d4-11e7-853e-bb676e8d6037.png)

**Comment by gstephen** [comment]
```jQuery
function addCommentNumbers() {
        AJS.$(".commentcount").remove();

        //Take into account collapsed comments
        var count = (jQuery('.show-more-comments').length === 0) ? 1 : (jQuery('.show-more-comments').data('collapsed-count') + 1);

        AJS.$('div[id|=comment][id!=comment-wiki-edit]').each(function () {
            AJS.$(this).prepend('<h3 class="commentcount">' + count + '</h3>');
            count = count + 1;
        });
    }

    AJS.$('document').ready(function () {
        addCommentNumbers();

        JIRA.bind(JIRA.Events.REFRESH_ISSUE_PAGE, function (e, context, reason) {
            addCommentNumbers();
        });
        JIRA.bind(JIRA.Events.NEW_CONTENT_ADDED, function (e, context, reason) {
            addCommentNumbers();
        });
    });```
